### PR TITLE
Fix typo (not -> now)

### PR DESCRIPTION
**Pull request by Francismori7**
:(

### CODE REVIEW

**Comment by zimbatm** [comment]
Thanks !

**Comment by leggetter** [comment]
Hi @Francismori7  - Thanks for the PR. Have you been working through the tutorials? Do you have any feedback?

**Comment by Francismori7** [comment]
Hi @leggetter,

I did. However, I went through it as reference or as a refresh rather. I have integrated Socket.IO myself with Redis on numerous projects of mine. I just went through it to see how different it would be - it's pretty much the same thanks to the interfaces.

So I cannot really give you feedback, seeing as my experience with web sockets is pretty advanced for a tutorial like this.

Very well written and is very easy going through it. 2 hours is a bit much for it however. I myself went through it in 15 minutes.

**Comment by leggetter** [comment]
Thanks, @Francismori7,

Yeah, redis pubsub and Pusher do offer similar APIs, with a slight difference being the evented nature of Pusher's API (`pusher.trigger(channelName, eventName data)` vs. `redis.publish(channelName, data)`). But then again socket.io is event-first (`socket.on('event-name')`). I think the main thing is that both these solutions work well with real-time apps.

The tutorial was built as something for somebody with reasonable JS and Laravel experience, so it sounds like the only value you would get is as a Pusher reference - which itself is definitely useful.

2 hours was for the workshop setting. Based on running it twice 2 hours was actually a bit tight for people to get through. But I can see how somebody who is familiar with the concepts could get through it much faster. 

This feedback is very useful. Thanks again.

**Pull request merged**
